
name: debian_for_capricorn
on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y binfmt-support qemu-user-static  kernel-package fakeroot simg2img img2simg mkbootimg bison libelf-dev flex gcc-aarch64-linux-gnu pkg-config libncurses-dev libssl-dev unzip git bc devscripts debhelper
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          
          sudo mkdir -p /mnt/chroot
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          sudo mkdir -p /rootfs/
          sudo mkdir -p /rootfs/tmp_mkboot
          sudo chown $USER:$GROUPS /rootfs
          sudo chown $USER:$GROUPS /rootfs/tmp_mkboot
          sudo chown $USER:$GROUPS /mnt/chroot
          cp *.sh /rootfs/
      - name: Download source code
        id: down
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          git clone --depth 1 https://gitlab.com/kschen202115/msm8996-6.9.git linux
          ls
      - name: Patch kernel
        id: patch
        run: |
          # cp  cjktty-6.9.patch linux/cjktty-6.9.patch
          cp config linux/arch/arm64/configs/msm8996_defconfig
          chmod +rw linux/arch/arm64/configs/msm8996_defconfig
          cd linux
          wget https://raw.githubusercontent.com/zhmars/cjktty-patches/refs/heads/master/cjktty-add-cjk32x32-font-data.patch
          wget https://raw.githubusercontent.com/kschen202115/Armbian-build/refs/heads/main/cjktty-6.9.patch
          export CROSS_COMPILE=aarch64-linux-gnu-
          export ARCH=arm64
          make clean
          make mrproper
          git apply cjktty-6.9.patch
          git apply cjktty-add-cjk32x32-font-data.patch
          git add .
          cd ..
      - name: Compile
        id: compile
        run: |
          cd linux
          export PATH=/usr/lib/llvm-19/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-gnu-
          export ARCH=arm64
          make msm8996_defconfig ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang-19 LD=ld.lld-19 LLVM=1 LTO=FULL KBUILD_CFLAGS="-flto"
          make deb-pkg ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang-19 LD=ld.lld-19 LLVM=1 LTO=FULL -j$(nproc)
          #make deb-pkg -j$(nproc)
          cd ..
          cp *.deb /workdir
          cp *.deb /rootfs
          cp linux/arch/arm64/boot/Image.gz /workdir
          cp linux/arch/arm64/boot/Image.gz /rootfs/tmp_mkboot/
          cp linux/arch/arm64/boot/dts/qcom/*capricorn*.dtb /rootfs/tmp_mkboot/
          tar -czf /workdir/msm8996_dtb.tar.gz linux/arch/arm64/boot/dts/qcom/*capricorn*.dtb
          find ./ -type f \( ! -name "*.ko" -a ! -name "modules.*" \) -exec rm -f {} \;
          cd linux/
          tar -czf /workdir/modules.tar.gz ./*
          cd ..
          echo "::set-output name=status::success"
      - name: Prepare Environment
        run: |
          cd /rootfs
          wget https://github.com/kschen202115/Port_Debian_for_capricorn/releases/download/Linux_Kernel_debian/root.zip
          unzip root.zip
          sudo rm -rf root.zip
          simg2img ./rootfs.img ./root.img
          sudo rm -rf rootfs.img
          sudo mount root.img /mnt/chroot
          sudo mount --bind /proc /mnt/chroot/proc
          sudo mount --bind /dev /mnt/chroot/dev
          sudo mount --bind /dev/pts /mnt/chroot/dev/pts
          sudo mount --bind /sys /mnt/chroot/sys
          # sudo mkdir -p /mnt/chroot/tmp
          sudo rm -rf  /mnt/chroot/tmp/linux-*.deb 
          cp linux-* /mnt/chroot/tmp
      - name: Install Kernel in chroot
        run: |
          sudo chroot /mnt/chroot /bin/bash -c "
            cd /tmp
            dpkg --get-selections | grep linux
            dpkg -l | grep -E 'linux-headers|linux-image' | awk '{print \$2}' | xargs dpkg -P
            rm -rf /lib/modules/*
            dpkg -i linux*.deb
            dpkg --get-selections | grep linux
            ls /lib/modules
          "
      - name: Build boot image
        run: |
          cd /rootfs/
          ls
          cp /mnt/chroot/boot/initrd* ./tmp_mkboot/
          cp ./tmp_mkboot/initrd* ./tmp_mkboot/initrd.img
          cp ./tmp_mkboot/*.dtb ./tmp_mkboot/dtb
          cat ./tmp_mkboot/Image.gz ./tmp_mkboot/dtb > ./tmp_mkboot/kernel-dtb
          mkbootimg --base 0x80000000 \
                    --kernel_offset 0x00008000 \
                    --ramdisk_offset 0x01000000 \
                    --tags_offset 0x00000100 \
                    --pagesize 4096 \
                    --second_offset 0x00f00000 \
                    --ramdisk ./tmp_mkboot/initrd.img \
                    --cmdline "console=tty0 root=UUID=cf0a4308-8a5e-4f83-8750-9dfe2bb0e336 rw loglevel=3 splash" \
                    --kernel ./tmp_mkboot/kernel-dtb -o ./tmp_mkboot/boot.img
          img2simg ./root.img ./rootfs.img
          zip root.zip rootfs.img
          cp root.zip /workdir/
          cp  ./tmp_mkboot/boot.img /workdir/
      - name: Upload image to Release
        uses: ncipollo/release-action@main
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          tag: debian_for_capricorn_with_clang
          artifacts: /workdir/*
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is Linux Kernel
